config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books do
    resources :reviews, only: [:new, :create, :show]
    resources :bookings, only: [ :new, :create ]
    resources :wishes, only: :create 
  end
  resources :wishes, only: :destroy

  resources :bookings, only: [ :show ] do 
    member do
      post :approve
      post :reject
    end
  end

  resources :users, only: [:show, :destroy] 
 
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
 
  include PgSearch::Model
  pg_search_scope :search_by_title_and_author,
    against: [ :title, :author ],
    using: {
      tsearch: { prefix: true } 
    }

  
  belongs_to :user
  has_many :bookings

  has_many :reviews, dependent: :destroy

  has_many :wishes


  validates :title, presence: true
  validates :author, presence: true
  validates :genre, presence: true
  validates :condition, presence: true
  validates :year, presence: true
  validates :publisher, presence: true
  validates :address, presence: true
  validates :price, presence: true
  validates :photo, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one_attached :photo

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :book
  belongs_to :user

  
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :book
    belongs_to :booking

    validates :content, presence: true

    validates :rating, numericality: { only_integer: true }
    validates :rating, inclusion: { in: (0..5).to_a }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :bookings
  has_many :incoming_bookings, through: :books, source: :bookings
  has_many :wishes
  has_one_attached :avatar
  has_one_attached :photo
end

app/models/wish.rb
class Wish < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

    def new
        @booking = Booking.new
        @book = Book.find(params[:book_id])
    end

    def create
        @booking = Booking.new(booking_params)
        @book = Book.find(params[:book_id])
        @booking.user = current_user
        @booking.book = @book
        if @booking.save!

            redirect_to booking_path(@booking)

           

        else
            render :new
        end
    end

  def show
    @booking = Booking.find(params[:id])
    @book = @booking.book
    @user = @booking.user
  end

  def approve
    @booking = Booking.find(params[:id])
    @booking.update(state: "Approved")
    redirect_to booking_path(@booking)
    # need to add a state file but confused wheather it should be boolean or string
    #as in like three strings one for pending, approved or rejected
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.update(state: "Rejected")
    redirect_to booking_path(@booking)
    # need to add a state file but confused wheather it should be boolean or string
    #as in like three strings one for pending, approved or rejected
  end


    private

    def booking_params
        params.require(:booking).permit(:start_date, :end_date, :price)
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
    def index
      if params[:query].present?
        @books = Book.search_by_title_and_author(params[:query])
      else
        @books = Book.all
      end
        @markers = @books.geocoded.map do |book|
          {
            lat: book.latitude,
            lng: book.longitude
          }
        end
    end
  
    def show
      @book = Book.find(params[:id])
      @review = Review.new
    end

    def new
      @book = Book.new
    end

    def create
      @book = Book.new(book_params)
        @book.user = current_user
          if @book.save!
            redirect_to book_path(@book)
          else
            render :new
          end
    end

    def destroy
      @book = Book.find(params[:id])
      @book.destroy
      redirect_to books_path
    end

    private

    def book_params
      params.require(:book).permit(:title, :author, :genre, :condition, :year, :price, :publisher, :photo, :address)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index
        @reviews = Review.all
    end

    
    def new
        @review = Review.new
        @book = Book.find(params[:book_id])
    end

    def create
        @review = Review.new(review_params)
        @book = Book.find(params[:book_id])
        @review.book = @book
        if @review.save
            redirect_to book_path(@book)
        else
            render 'books/show'
        end
    end

    private

    def review_params
        params.require(:review).permit(:content, :rating, :booking_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = current_user
        @wishes = @user.wishes
        #how do i create upload just an image avatar
        # redirect_to user_path(@user)
    end
    # we need to only create the photo for which the user already exist

end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController

  def create
    @wish = Wish.new
    @book = Book.find(params[:book_id])
    @wish.user_id = current_user.id
    @wish.book_id = @book.id
      if @wish.save
        redirect_to books_path
      else
        render :new
      end
  end


  def destroy
    @wish = Wish.find(params:[:id])
    @wish.destroy

  end  

   




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<body class="booking-page">
<div class="d-flex">
  <div class="flex-header">
    <h1 class="land-header mb-4"> Make a booking </h1>
    <h2 class="land-subheader"> Lend your book now! </h2>
  </div>
  <div class="flex-form">
  <div class="container-book d-flex flex-column">
    <h3 class="make-a-booking"> Choose the period you want to lend the book</h3>
    <%= simple_form_for [@book, @booking] do |f| %>
      <%= f.input :start_date, class: "date-text"%>

      <%= f.input :end_date, class: "date-text" %>

      <%= f.submit :submit, class: "btn mt-5 mb-3" %>

<!--       <main>
  <div class="button">
    <div class="text"> <%= f.submit :submit%></div>
  </div>
  <div class="progress-bar"></div>
  <svg x="0px" y="0px"
   viewBox="0 0 25 30" style="enable-background:new 0 0 25 30;">
    <path class="check" class="st0" d="M2,19.2C5.9,23.6,9.4,28,9.4,28L23,2"/>
  </svg>
</main> -->

    <% end %>
  </div>
</div>
</div>
<br><br><br><br><br><br><br><br>
</body>

app/views/bookings/show.html.erb
<body class="show-booking">
 <div class="d-flex justify-content-between">
  <div class="title-author">
    <h1>Your booking is <%= @booking.state %>!</h1>
    <h2>Please check if the information below is correct</h2>
  </div>

    <div class="pending-container">
    <h2><%= @booking.state %></h2>
  </div>
</div>
<div class="d-flex justify-content-between">

    <div>
      <%= cl_image_tag @book.photo.key, height: 400, width: 600, crop: :fill, class: "show-photo" %>
    </div>

  <div class="date-container">
      <h3 class="text-price"> PRICE </h3>
      <h1 class="text-price-booking"><%= @book.price %> £</h1>
      <h4 class="date-text">start date</h4>
      <h3 class="text-price-booking"><%= @booking.start_date %></h3>
      <h4 class="date-text">end date</h4>
      <h3 class="text-price-booking"><%= @booking.start_date %></h3>
      <div class="btn-manage-booking"><%= link_to "Manage your bookings", user_path(@user), class: "btn-color" %></div>
    </div>
</div>
<hr class="divide-member-3">
  <div class="member-info-booking d-flex justify-content-between">
    <div>
    <h3>Book posted by</h3>
    <h4><%= @book.user.email %></h4>
    </div>
    <div>
      <% if @book.user.avatar.attached? %>
        <%= cl_image_tag @book.user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <%= image_tag "user.svg", class: "avatar dropdown-toggle" %>
      <% end %>
    </div>
  </div>

  <hr class="divide-member">

  <div class="show-container d-flex justify-content-between">

    <div class="book-details">
      <div class="book-detail-1 d-flex">
         <div class="icon-details"><%= image_tag "title.svg" %></div>
         <h4><%= @book.title %></h4>
      </div>
      <div class="book-detail d-flex">
         <div class="icon-details"><%= image_tag "writer.svg" %></div>
         <h4><%= @book.author %></h4>
      </div>
      <div class="book-detail d-flex">
         <div class="icon-details"><%= image_tag "publisher.svg" %></div>
         <h4><%= @book.publisher %></h4>
      </div>
      <div class="book-detail d-flex">
        <div class="icon-details"><%= image_tag "genre.svg" %></div>
        <h4><%= @book.genre %></h4>
      </div>
       <div class="book-detail d-flex">
        <div class="icon-details"><%= image_tag "condition.svg" %></div>
      <h4><%= @book.condition %></h4>
    </div>
     <div class="book-detail d-flex">
        <div class="icon-details"><%= image_tag "year.svg" %></div>
      <h4><%= @book.year %></h4>
    </div>
  </div>




</div>

<hr class="divide-member-2">

</body>

app/views/books/index.html.erb
<body class="body-index">
<h1 class="header-index"> Books you might like. </h1>




<form class="form-inline">
  <div class="form-group mx-sm-3 mb-2">
<%= form_tag books_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a book"
  %>
</div>
<div><%= submit_tag "Search", class: "btn-search-form" %></div>
<% end %>
</form>



<div class="map-cards d-flex">
<div class="card-container ">
    <% @books.each do |book| %>
      <div class="card-product">
        <div class="card-product-infos">
          <div class="image-display">
              <% if book.photo.attached? %>
                <%= cl_image_tag book.photo.key, height: 200, width: 260, crop: :fill%>
              <% else %>
                <%= image_tag "https://www.pluggedin.com/wp-content/uploads/2020/01/placeholder_book.jpg", style: "height: 300; width: 400;" %>
            <% end %>
          </div>

          <h4><%= link_to book.title, book_path(book), class: "book-title-index" %> </h4>
          <h5><%= book.author %> </h5>
          <p><em> Belongs to <%=book.user.email%></em></p>
          <p><em>On <%=book.created_at.strftime("%A, %b %d")%></em></p>
          <%#= link_to "Remove", book_path(book), method: :delete, :class => "btn-remove" %>

         <p class="wishlist"><%= link_to 'Add to wishlist', book_wishes_path(book.id), method: :post, class: "wishlist" %></p>



          </div>

        </div>

    <%end%>
</div>

<div id="map" class="index-books-map"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>
</div>



</body>

app/views/books/new.html.erb
<body class="land-page">
<div class="d-flex">
  <div class="flex-header">
<h1 class="land-header"> Lend to others </h1>
<h2 class="land-subheader"> Become a member! </h2>
  </div>
  <div class="flex-form">
<div class="container-land d-flex flex-column">
<%= simple_form_for(@book) do |f| %>
 <div class="p-2 col-xs-2">
  <%= f.input :title, class: "land-label" %>
  <%#= f.text_field :title, class: "form-control" %>
</div>
<div class='p-2'>
  <%= f.input :author, class: "land-label" %>
  <%#= f.text_field :author, class: "form-control" %>
</div>
<div class='p-2'>
  <%= f.input :genre, class: "land-label" %>
  <%#= f.text_field :genre, class: "form-control" %>
</div>
<div class='p-2'>
  <%= f.input :condition, class: "land-label" %>
  <%#= f.text_field :condition, class: "form-control" %>
</div>
<div class='p-2'>
  <%= f.input :year, class: "land-label" %>
  <%#= f.number_field :year, class: "form-control" %>
</div>
<div class='p-2'>
  <%= f.input :publisher, class: "land-label" %>
  <%#= f.text_field :publisher, class: "form-control" %>
</div>
<div class='p-2'>
  <%= f.input :price, class: "land-label" %>
  <%#= f.number_field :price, class: "form-control" %>
</div>
<div class='p-2'>
  <%= f.input :address, class: "land-label" %>
  <%#= f.text_field :address, class: "form-control" %>
</div>
<div class='p-2'>
<%= f.input :photo, as: :file %>
</div>
<div class= "p-2 justify-content-center">
  <%= f.submit :submit, class: "btn" %>
</div>
<% end %>
</div>
</div>
</div>
</body>

app/views/books/show.html.erb
<body class="show-page">
  <div class="show-padding">
  <div class="title-author">
    <h3><%= @book.title %></h3>
    <h3><%= @book.author %></h3>
  </div>
  <div class="d-flex justify-content-between mb-5">
    <div>
      <%= cl_image_tag @book.photo.key, height: 300, width: 500, crop: :fill, class: "show-photo" %>
    </div>
    <div class="d-flex flex-column">
    <div class="book-price">
      <h1><span style="font-size:15px;">price: &#8287;</span><%= @book.price %> £</h1>
      <% unless @book.user == current_user %>
        <div class="btn-make-booking">
          <%= link_to "Make a booking", new_book_booking_path(@book), class: "btn-color" %>
        </div>
      <% end %>
    </div>

<div class="book-details">
  <h4 class="book-details"> Book Deatils </h4>
  <hr class="hr-details">
      <div class="book-detail-1 d-flex">
         <div class="icon-details"><%= image_tag "publisher.svg" %></div>
         <h5><%= @book.publisher %></h5>
      </div>
      <div class="book-detail d-flex">
        <div class="icon-details"><%= image_tag "genre.svg" %></div>
        <h5><%= @book.genre %></h5>
      </div>
       <div class="book-detail d-flex">
        <div class="icon-details"><%= image_tag "condition.svg" %></div>
      <h5><%= @book.condition %></h5>
    </div>
     <div class="book-detail d-flex">
        <div class="icon-details"><%= image_tag "year.svg" %></div>
      <h5><%= @book.year %></h5>
    </div>
  </div>
</div>


  </div>

<hr class="divide-member">

  <div class="member-info d-flex justify-content-between">
    <div>
    <h3>Book posted by</h3>
    <h4><%= @book.user.email %></h4>
    </div>
    <div>
      <% if @book.user.avatar.attached? %>
        <%= cl_image_tag @book.user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <%= image_tag "user.svg", class: "avatar dropdown-toggle" %>
      <% end %>
    </div>
  </div>

  <hr class="divide-member">

  <div class="reviews d-flex justify-content-between">


<div class="posted-reviews">

<h2> Reviews </h2>

    <% @book.reviews.each do |rev| %>
  <% if rev.booking %>
<div class="d-flex flex-column">
      <div class="d-flex">
    <div>
    <p class="poster-user"><%= rev.booking.user.email %></p>
  </div>
  <div class="rating-content">
    <p class="posted-content">content:&#8287;&#8287;<%= rev.content  %> </p>
    <p class="posted-rating">rating:&#8287;&#8287;<%= rev.rating  %> </p>
  </div>
  </div>
  </div>
  <% end %>

<% end %>


</div>

 <div class="review-container">
<h3> Add a review </h3>
<%if current_user.bookings.joins(:book).where("books.id in (?)", @book.id).any? %>
  <%= form_for [@book, @review] do |f| %>
    <div class="d-flex justify-content-between">
    <%= f.label :content, class: "review-label" %>
    <%= f.text_field :content, class: "review-field" %>
  </div>
  <div class="d-flex justify-content-between">
    <%= f.label :rating, class: "review-label" %>
    <%= f.text_field :rating, class: "review-field" %>
  </div>
    <%=  f.hidden_field :booking_id, value: Booking.find_by(user: current_user, book: @book).id %>
    <%= f.submit :submit, class: "review-submit" %>
  <% end %>
<%end%>
  </div>

</div>

<hr class="divide-member-2">

</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTextbookExchange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link href="https://fonts.googleapis.com/css?family=Poppins:600" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
    crossorigin="anonymous">

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="main-content"><%= yield %></div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<% provide(:nav_style, "transparent-nav") %>

<%= video_tag "student.mp4", autoplay: :autoplay, loop: :loop, muted: :muted, class: "home-video" %>


<h1 class="form-message"> Find your book here </h1>

<form class="form-inline">
  <div class="form-group mx-sm-3 mb-2">
    <input type="text" class="form-control" placeholder="type in title, author, publisher...">
  </div>
  <button type="submit" class="btn btn-primary mb-2">Search</button>
</form>

<% provide(:footer_style, "transparent-footer") %>

app/views/shared/_footer.html.erb
<footer class="page-footer font-small darken-3 <%= yield(:footer_style) %>">
  <div class="container-footer d-flex justify-content-between">
    <a class="fb-ic">
      <i class="fab fa-facebook-f fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
    </a>
    <a class="tw-ic">
      <i class="fab fa-twitter fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
    </a>
    <a class="gplus-ic">
      <i class="fab fa-google-plus-g fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
    </a>
    <a class="li-ic">
      <i class="fab fa-linkedin-in fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
    </a>
    <a class="ins-ic">
      <i class="fab fa-instagram fa-lg white-text mr-md-5 mr-3 fa-2x"> </i>
    </a>
    <a class="pin-ic">
      <i class="fab fa-pinterest fa-lg white-text fa-2x"> </i>
    </a>
  </div>
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    Exchange Textbooks
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= yield(:nav_style) %>" >
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "just-logo.svg", class: "logo-navbar" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Browse", books_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Lend to others", new_book_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.avatar.attached?%>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "user.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Become a member", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
       <li class="nav-item">
          <%= link_to "Browse", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Lend to others", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<body class="profile-page">
<h1 class="user-header">Manage all your <span style="color: #2a9d8f; font-size: 40px;">books</span> and bookings in one page! </h1>
<div class="container" id="container">
        <div class="form-container sign-up-container">
            <form action="#">
                <div>
                  <% if @user.books.exists? %>

                      <div class="card-container-user">
                       <% @user.books.each do |book| %>
                        <% book.bookings.each do |booking| %>
                        <div class="card-product-user">

                           <div class="image-display-user">
                        <% if book.photo.attached? %>
                          <%= cl_image_tag book.photo.key, height: 100, width: 180, crop: :fill%>
                        <% else %>
                          <%= image_tag "https://www.pluggedin.com/wp-content/uploads/2020/01/placeholder_book.jpg", style: "height: 300; width: 400;" %>
                      <% end %>
                    </div>
                      <%= booking.start_date %>
                          <%= booking.end_date %>
                          <% if booking.book.user == current_user %>
                              <%= link_to 'Approve', approve_booking_path(booking), class: "button-xs success", method: :post %>
                              <%= link_to 'Reject', reject_booking_path(booking), class: "button-xs success", method: :post %>
                              <% end %>

                     </div>
                          <% end %>
                       <% end  %>

                     </div>
                      <% else %>
                      <p> "You don't have any bookings" </p>
                  <% end %>
              </div>
            </form>
        </div>
        <div class="form-container sign-in-container">
            <form action="#">
                <div>
    <% if @user.books.exists? %>
    <div class="card-container-user">
         <% @user.books.each do |book| %>
          <div class="card-product-user">
             <div class="image-display-user">
              <% if book.photo.attached? %>
                          <%= cl_image_tag book.photo.key, height: 100, width: 180, crop: :fill%>
                        <% else %>
                          <%= image_tag "https://www.pluggedin.com/wp-content/uploads/2020/01/placeholder_book.jpg", style: "height: 300; width: 400;" %>
                      <% end %>
                    </div>
           <p class="user-book-info-title"> <%= book.title%></p>
           <p class="user-book-info"> <%= book.author %></p>
          <p class="user-book-info"> <%= book.genre %></p>

          </div>
        <% end %>
        </div>
    <% else %>
        <p>You don't have any books</p>
    <% end %>

</div>

            </form>
        </div>
        <div class="overlay-container">
            <div class="overlay">
                <div class="overlay-panel overlay-left">
                    <h1>My books</h1>
                    <h5>User email: <%= @user.email %> </h5>
                    <p>Manage all your books here!</p>
                    <button class="ghost" id="signIn">My bookings</button>
                </div>
                <div class="overlay-panel overlay-right">
                    <h1>My bookings</h1>
                    <h5>User email: <%= @user.email %> </h5>
                    <p>Keep track of your bookings!</p>
                    <button class="ghost" id="signUp">My books</button>
                </div>
            </div>
        </div>
    </div>


<h1 class="user-header-wish mb-5">My wishlist.</h1>
<div class="wishlist-container d-flex justify-content-center">
<% if @wishes.any? %>
    <% @wishes.each do |wish| %>
    <div class="card-product-wish">
    <p class="user-book-info-title" style="color: #e76f51;"> <%= wish.book.title%></p>
     <p class="user-book-info"> <%= wish.book.author %></p>
    <p class="user-book-info"> <%= wish.book.genre %></p>
    <p class="user-book-info"> <%= wish.book.publisher %></p>
  </div>
    <%end %>
<% else %>
 <p class="user-book-info">Nothing in your wishlist!</p>
<% end %>
</div>


<br><br><br><br><br>

</body>

</div>
</div>




</body>